//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendees
    {
        public int IdAttendees { get; set; }
        public int IdMeetings { get; set; }
        public int IdStaff { get; set; }
    
        public virtual Meetings Meetings { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
