//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int IdDocuments { get; set; }
        public string TitleDocuments { get; set; }
        public string DescriptionDocuments { get; set; }
        public int IdCategory { get; set; }
        public int IdStaff { get; set; }
        public System.DateTime UploadDate { get; set; }
        public byte[] FileDocuments { get; set; }
        public int QuantityPage { get; set; }
        public int QuantityОfСopies { get; set; }
        public System.DateTime DateOfExecution { get; set; }
        public string NameDocuments { get; set; }
        public Nullable<int> IdMarkExecution { get; set; }
    
        public virtual DocumentsCategory DocumentsCategory { get; set; }
        public virtual MarkExecution MarkExecution { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
