//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingDocuments
    {
        public int IdIncomingDocuments { get; set; }
        public int NumberIncoming { get; set; }
        public System.DateTime DateIncoming { get; set; }
        public int IdCategory { get; set; }
        public byte[] FileDocuments { get; set; }
        public int IdSender { get; set; }
        public string NameIncoming { get; set; }
        public string SummaryIncoming { get; set; }
        public int IdStaff { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public int OutgoingNumber { get; set; }
        public Nullable<System.DateTime> DateOutgoingNumber { get; set; }
        public System.DateTime ControlDate { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public int IdMarkExecution { get; set; }
        public int QuantityОfСopies { get; set; }
        public int QuantityPage { get; set; }
    
        public virtual DocumentsCategory DocumentsCategory { get; set; }
        public virtual MarkExecution MarkExecution { get; set; }
        public virtual Sender Sender { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
