//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meetings()
        {
            this.Attendees = new HashSet<Attendees>();
        }
    
        public int IdMeetings { get; set; }
        public System.DateTime MeetinsDate { get; set; }
        public string MeetingsTime { get; set; }
        public string MeetingsDuration { get; set; }
        public string AgendaMeetigns { get; set; }
        public int IdStaff { get; set; }
        public int IdDepartments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendees> Attendees { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
