//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemembersTokken
    {
        public int IdRemembersTokken { get; set; }
        public int IdUser { get; set; }
        public string Tokken { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
