//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevDiplom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int IdTasks { get; set; }
        public int IdStaff { get; set; }
        public string AssignedToTasks { get; set; }
        public string CompletedTasks { get; set; }
        public System.DateTime DueData { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
